apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cert-customizations
  namespace: kube-system
  labels:
    app: cert-customizations
spec:
  selector:
    matchLabels:
      app: cert-customizations
  template:
    metadata:
      labels:
        app: cert-customizations
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: cert-customizations
        image: marketplace.gcr.io/google/ubuntu2004
        command: ["/scripts/load-certs.sh"]
        volumeMounts:
        - name: etc
          mountPath: "/mnt/etc"
        - mountPath: /registry
          name: registry-cert
          readOnly: true
        - mountPath: /scripts
          name: scripts
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
      volumes:
      - name: etc
        hostPath:
          path: /etc
      - name: scripts
        configMap:
          name: load-certs-script
          defaultMode: 0744
      - name: registry-cert
        secret:
          secretName: registry-pem
          defaultMode: 420
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
      tolerations:
        - effect: NoSchedule
          operator: Exists
