apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: registry.samos-it.com/nginx
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
