apiVersion: v1
kind: ConfigMap
metadata:
  name: load-certs-script
  namespace: kube-system
data:
  load-certs.sh: |
    #!/usr/bin/env bash
    set -xe

    export REGISTRY_FQDN=registry.example.com

    echo "Deleting the custom certificate folder and creating it again"
    rm -rf /mnt/etc/docker/certs.d/$REGISTRY_FQDN
    mkdir -p /mnt/etc/docker/certs.d/$REGISTRY_FQDN

    echo "Copying the custom certificate"
    cp /registry/cert.crt /mnt/etc/docker/certs.d/$REGISTRY_FQDN/cert.crt
    echo "Certificates copied"

    # only containerd requires a restart
    nsenter --target 1 --mount bash -c "systemctl is-active --quiet containerd && echo 'Restarting containerd' && systemctl restart containerd"
    

